Flask Exercise III/website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'XXX'

    from .views import views

    app.register_blueprint(views, url_prefix='/')

    return app

Flask Exercise III/website/views.py
from asyncio import selector_events
from flask import request, flash, redirect, Blueprint, render_template
import os
from werkzeug.utils import secure_filename
from search_engine.handler import Handler
import json

views = Blueprint('views', __name__)

APP_ROOT = os.path.dirname(os.path.abspath(__file__))
QUERY_FOLDER = f'static{os.sep}uploaded'
PACKAGE = 'website'
##DATA_FOLDER = f'search_engine{os.sep}data{os.sep}images{os.sep}training'

ALLOWED_EXT = ['jpg', 'png']
handler = Handler()
selected_image = ""
selected_images = []
not_selected_images = []

@views.route("/")
def index():
    global selected_image
    return render_template("start.html", selected_image=selected_image)# selected_image)

@views.route("/selected_image", methods=['POST', 'GET'])
def select_query_image():

    if request.method == 'GET':
        return index()

    global selected_image
    global handler
    target = os.path.join(APP_ROOT, QUERY_FOLDER)

    if os.path.isdir(target) == False:
        os.mkdir(target)

    if request.method == 'POST':
    
        file = request.files['file']
        if not file:
            flash(f'No file chosen', 'error')
            return redirect('/')

        filename, ext = secure_filename(file.filename.lower()).split('.')
        if ext not in ALLOWED_EXT:
            flash(f'Invalid filetype: .{ext}', 'error')
            return redirect('/')

        selected_image = f'{filename}.{ext}'
        file_path = os.path.join(target, selected_image)
        file.save(file_path)

        return render_template("start.html", selected_image = selected_image)

@views.route("/query_result", methods=['POST', 'GET'])
def start_query():
    global selected_image
    global query_results
    global handler

    if request.method == 'GET':
        if query_results:
            return render_template("query_result.html", selected_image = selected_image, query_results = query_results)
        else:
            return redirect('/')

    image_name = selected_image.split('.')[0]

    flash(f'Searching', 'success')

    image_path = os.path.join(PACKAGE, QUERY_FOLDER, selected_image)

    query_results = handler.query(image_path)

    print(query_results, flush=True)

    return render_template("query_result.html", selected_image = selected_image, query_results = query_results)

@views.route("/modified_result", methods=['POST', 'GET'])
def modified_query():
    global handler
    global query_results

    if request.method == 'POST':
        
        json_data = json.loads(request.get_data())
        selected_images = [_ for _ in json_data["selected_images"].split(';')][:-1]
        not_selected_images = [_ for _ in json_data["not_selected_images"].split(';')][:-1]

        print("printing not selected items:")
        print(not_selected_images)

        print("Query")

        query_results = handler.relevance_feedback(selected_images, not_selected_images) #SEQ.Query().relevance_feedback(selected_images, not_selected_images)
        print("Results:")

        query_results = [("images/" + Q[0].split("\\")[3], Q[1]) for Q in query_results]
        print(query_results)

        return 'response',200

    return render_template("query_result.html", selected_image = selected_image, query_results = query_results)

Flask Exercise III/website/templates/main_page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Medical information retrieval</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  
</head>

<body>

  
  <div class="jumbotron text-center" style="height: 220px;margin-bottom:0">
    <div class="row">
    <!-- Top banner
     banner/header with a logo in first three columns, project name in six columns and 
     university logo in last three columns

     -->
     <!-- pass-->  
      <div class = "col-md-3">
        <img src="static/retrieval_logo.png", style = "max-height: 150px; width: auto;">
      </div>
      <div class = "col-md-6">
        <h1>Medical information Retrieveal (MIR)</h1>
      </div>
      <div class = "col-md-3">
        <img src = "static/uni_logo.png", style = "max-height: 150px; width: auto;">
      </div>
    </div>
  
  <!-- Main part -->
  {% block body %}{% endblock %}
  </div>
</body>

</html>

Flask Exercise III/website/templates/query_result.html
{% extends "main_page.html" %}
{% block body %}
<div class="container" style="margin-top:10px;">
  <!-- Left info bar -->
  <div class="row">
    <div class="col-sm-2">
      <h3>Overview</h3>
       <!--ToDO:-->
    <!--Write HTML to show a left menu with values/items (Select image, Query result,Settings)  -->
    <!--pass-->
      <ul class="navbar-nav">
        <li class = "nav-item">
          <a class="nav-link activate">Select image</a>
        </li>
        <li class = "nav-item">
          <a class="nav-link disabled">Query results</a>
        </li>
        <li class = "nav-item">
          <a class="nav-link" href="#">Settings</a> 
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>

    <div class="col-sm-8">
      <h1 class="page-header" style="text-align: left;">Input image</h1>
      <div class="row">
        <div class = "col" style="width: 50%; text-align: left;">
          <img src="{{ url_for('static', filename = 'uploaded/' + selected_image) }}"
          style="max-height: 220px; 
          width: auto"
          alt="">
        </div>
        <div class="col" style="background-color: green;">
          :)
        </div>
      </div>
      <h1 class="page-header" style="text-align: left;">Query results</h1>
        {% for image in query_results %}
          <div class="row">
            <div class="col" style="max-height: 228px; width: 50%; text-align: left;">
              <div class = "notSelected" onclick="select_image(this)" style="max-height: 228px; width: auto; display: inline-block; border: 4px solid #FFFFFF;">
                <img src="{{url_for('static', filename=image[0])}}" style="max-height: 220px; width: auto; display: block;"
                >
              </div>            
            </div>
            <div class="col" style="text-align: left; background-color: green;">
              {{ image[1] }}
            </div>
          </div>
          <div style="height: 10px"></div>
        {% endfor %}
      
      <div style="height: 50px"></div>
    </div>

    <div class = "col-sm-2">
      <!-- <form id = "Relevance_feedback" action = "{{ url_for('views.modified_query') }}" method="POST" enctype="multipart/form-data"> -->
      <button type="submit" class="btn btn-primary" style="margin-top: 210px" onclick = "relevance_feedback()">Relevance feedback</button>

      <!-- TODO: Get relevant and irrelevant images -->
    </div>

  </div>
</div>
</body>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
  function select_image(element) {
    if(element.className == "selected") {
      element.className = "notSelected";
      element.style.border = "4px solid #FFFFFF";
    } else {
      element.className = "selected";
      element.style.border = "4px solid #8090CC";
    }
  }

  function relevance_feedback () {
    let selected_elements = document.getElementsByClassName("selected");
    let not_selected_elements = document.getElementsByClassName("notSelected");

    let selected_images = "";
    let not_selected_images = "";

    for (let i = 0; i < selected_elements.length; i++) {
      selected_images += selected_elements[i].innerHTML.split("/")[3].split('"')[0].toString()+";";
    }

    for (let i = 0; i < not_selected_elements.length; i++) {
      not_selected_images += not_selected_elements[i].innerHTML.split("/")[3].split('"')[0].toString()+";";
    }

    let body = {
      "selected_images": selected_images,
      "not_selected_images": not_selected_images
    };

    fetch('/modified_result', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
      }).then(function(response) {
      console.log("r1", response);
      if(!response.ok) {
        throw Error(response.statusText);
      }
      return response
    })
    .then(function(response){console.log("r2", response);window.location.href='/modified_result';})

    // fetch('/modified_result', {
    //   method: 'POST',
    //   headers: {
    //     'Content-Type': 'application/json'
    //   },
    //   body: JSON.stringify(body)
    //   })
    // .then(function(response) {
    //   alert(JSON.stringify(response))
    //   console.log("r1", response);
    //   if(!response.ok) {
    //     alert("!response.ok")
    //     throw Error(response.statusText);
    //   }
    //   return response})
    // .then(function(response) { console.log("r2", response); window.location.href='/relevance_feedback'; })
 }
</script>

</html>

{% endblock %}

Flask Exercise III/website/templates/show_image.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Medical information retrieval</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  </style>
</head>

<body>
  <p>File uploaded successfully</p>  
  <p>File Name: {{name}}</p> 
</body>

</html>

Flask Exercise III/website/templates/start.html
<!-- extend the page from main page-->
<!-- make the whole page a block body so that the content of the page can be shown in  main_page.html-->
<!--pass-->

{% extends "main_page.html" %}
{% block body %}

<div class="container" style="margin-top:10px">
  <!-- Left info bar -->
  <div class="row">
    <!--ToDO: DONE-->
    <!--Write HTML to show a left menu with values/items (Select image, Query result,Settings)  -->
    <!--pass-->

    <div class = "col-sm-3">
      
      <nav class="navbar">
        <div><h2>Overview</h2></div>
        <br/> 
        <ul class="navbar-nav">
          <li class = "nav-item">
            <a class="nav-link activate">Select image</a>
          </li>
          <li class = "nav-item">
            <a class="nav-link disabled">Query results</a>
          </li>
          <li class = "nav-item">
            <a class="nav-link" href="#">Settings</a> 
          </li>
        </ul>
      </nav>
    </div>

    <div class="col-sm-9">
      <h1 class="page-header">Input image</h1>
      <!--ToDO: DONE-->
      <!--Write HTML to show the uploaded query image -->
      <!--esle show any empty.png here -->
      <!--pass-->


      {% if selected_image %}
      <img src="{{ url_for('static', filename = 'uploaded/' + selected_image) }}" style="max-height: 300px; width: auto;">
      {% else %}
      <img src="static/empty.png" style="max-height: 300px; width: auto;">
      {% endif %}

      
      
      <p>Select an image via the file picker and press upload. Afterwards you can retrieve similar images.</p>

      <div class="row">
        <div class="col">
          
            <form id="upload-form" action="{{ url_for('views.select_query_image') }}" method="POST"
            enctype="multipart/form-data">
            <input class="button" id="file-picker" type="file" name="file" accept="image/*" multiple>
            <button type="submit" class="btn btn-primary" >Upload!</button>
          </form>
        </div>
        <div class="col">
          <form id="upload-form" action="{{ url_for('views.start_query') }}" method="POST" 
          enctype="multipart/form-data">
           
             <!--ToDO: DONE-->
             <!--Write HTML to show a Retrieve similar button if the query image is uploaded -->
             <!--esle disable the  Retrieve similar button -->
             <!--pass-->

            {% if selected_image %}
            <button type="submit" class="btn btn-primary">Retrieve similar</button>
            {% else %}
            {% endif %}
            
          </form>
        </div>
        
      </div>
    </div>
  </div>
</div>

{% endblock %}

Flask Exercise III/website/templates/upload.html
<html>
   <body>
      <form action = "/show_image" method = "POST" 
         enctype = "multipart/form-data">
         <input type = "file" name = "file" />
         <input type = "submit"/>
      </form>
   </body>
</html>